(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function f(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var g=f(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var l;a:{var m={a:!0},n={};try{n.__proto__=m;l=n.a;break a}catch(a){}l=!1}h=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=h;
function q(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.Y=b.prototype};function r(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var t=[150,250,400];function u(){var a=HTMLElement.call(this)||this;a.R=!1;return a}q(u,HTMLElement);u.prototype.initialize=function(){};u.prototype.render=function(){};u.prototype.handlePointerUpdate=function(){this.R=!0};u.prototype.handlePointerOut=function(){this.R=!1};u.prototype.shouldRenderOnHoverWhilePaused=function(){return!1};var w="contract-hold xcontract ycontract xcurves ycurves expand-hold xexpand yexpand speed".split(" ");function x(){var a=u.call(this)||this;a.N=[];a.F=[];a.K=!1;return a}q(x,u);x.prototype.connectedCallback=function(){this.j=1E3*Math.max(0,r(this,"contract-hold",0));this.B=y(this,"xcontract");this.C=y(this,"ycontract");this.H=r(this,"xcurves",1);this.I=r(this,"ycurves",1);this.D=1E3*Math.max(0,r(this,"expand-hold",0));this.v=y(this,"xexpand");this.A=y(this,"yexpand");this.T=r(this,"speed",25);z(this)};
x.prototype.attributeChangedCallback=function(a,b,c){if(this.K&&b!==c){switch(a){case "contract-hold":this.j=1E3*Math.max(0,r(this,"contract-hold",0));break;case "xcontract":this.B=y(this,"xcontract");break;case "ycontract":this.C=y(this,"ycontract");break;case "xcurves":this.H=r(this,"xcurves",1);break;case "ycurves":this.I=r(this,"ycurves",1);break;case "expand-hold":this.D=1E3*Math.max(0,r(this,"expand-hold",0));break;case "xexpand":this.v=y(this,"xexpand");break;case "yexpand":this.A=y(this,"yexpand");
break;case "speed":this.T=r(this,"speed",25)}z(this);A(this)}};function z(a){a.X=(a.C+a.A)/2;a.V=(a.C-a.A)/2;a.W=(a.B+a.v)/2;a.U=(a.B-a.v)/2;a.P=1E-4*a.T;a.s=Math.PI/a.P;a.o=a.s/2}function y(a,b){a=r(a,b,25);return Math.max(0,Math.min(100,a))/100}x.prototype.initialize=function(a,b,c){this.u=this.parentElement.querySelector("canvas").getContext("2d");this.O=this.parentElement.clientWidth*c;this.J=this.parentElement.clientHeight*c;this.m=b[0];A(this);this.K=!0};
function A(a){a.l=[];if(void 0!==a.m){var b=a.m.naturalWidth*(1+(1===a.H?a.v:Math.max(a.v,a.B))),c=a.m.naturalHeight*(1+(1===a.I?a.A:Math.max(a.A,a.C))),e=Math.min(a.O/b,a.J/c);a.i=b*e;a.h=c*e;a.M=a.m.naturalWidth*e;a.L=a.m.naturalHeight*e;a:{b=Math.sqrt(a.i*a.h);for(c=0;c<t.length;c++)if(b<=t[c]){b=c+1;break a}b=t.length+1}a.g=b;a.G=a.ownerDocument.createElement("canvas");a.G.width=Math.ceil(a.i);a.G.height=Math.ceil(a.h);a.S=a.G.getContext("2d");for(b=0;b<a.i;b+=a.g)c=a.ownerDocument.createElement("canvas"),
c.width=a.g,c.height=a.h,c.getContext("2d").drawImage(a.m,-b,0,a.i,a.h),a.l.push(c);a.N=[];a.F=[];if(a.l&&a.l.length){for(b=0;b<a.l.length;b++)a.N.push(Math.sin((b+.5)/a.l.length*(2*a.I-1)*Math.PI)*a.L/2);b=Math.ceil(a.h/a.g);for(c=0;c<b;c++)a.F.push(Math.sin((c+.5)/b*(2*a.H-1)*Math.PI)*a.M/2)}}}
x.prototype.render=function(a){if(this.K){a<this.o||(a=(a-this.o)%(2*this.s+this.D+this.j),a=a<this.j?this.o:a<this.j+this.s?this.o+a-this.j:a<this.j+this.s+this.D?this.o+this.s:this.o+a-this.j-this.D);this.S.clearRect(0,0,this.i,this.h);a=Math.sin(a*this.P);var b=a*this.X+this.V;a=a*this.W+this.U;for(var c=(this.h-this.L)/2,e=(this.i-this.M)/2,k=0;k<this.l.length;k++){var v=this.N[k]*b;this.S.drawImage(this.l[k],k*this.g,c+v,this.g,this.L-2*v)}this.u.save();this.u.clearRect(0,0,this.O,this.J);this.u.translate((this.O-
this.i)/2,(this.J-this.h)/2);for(b=0;b<this.F.length;b++)c=this.F[b]*a,this.u.drawImage(this.G,0,b*this.g,this.i,this.g,e+c,b*this.g,this.M-2*c,this.g);this.u.restore()}};g.Object.defineProperties(x,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return w}}});customElements.define("gwd-breathe",x);}).call(this);
